language: common-lisp

env:
  matrix:
    - LISP=sbcl

install:
  # Install cl-travis
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  # Clone the latest copies of external libraries
  - git clone https://github.com/fukamachi/lack.git ~/lisp/lack
  - git clone https://github.com/fukamachi/clack.git ~/lisp/clack
  - git clone https://github.com/fukamachi/ningle.git ~/lisp/ningle

script:
  - cl -l fiveam -l closure-template
       -e '(setf fiveam:*debug-on-error* t)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(ql:quickload :clack-errors-test)'

notifications:
  email:
    - eudoxiahp@gmail.com
